# These are supported funding model platforms
open_collective: # Replace with a single Open Collective username
ko_fi: mknoph
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
